In [ ]:
import open3d as o3d
import numpy as np
print("Load a ply point cloud, print it, and render it")
# Complete point cloud
pcd = o3d.io.read_point_cloud("/home/zichen/Downloads/Datasets_Unpack/ShapeNetCompletion/test/complete/02691156/1169d987dbbce76775f4ea0b85a53249.pcd")
print(pcd)
print(np.asarray(pcd.points))
o3d.visualization.draw_geometries([pcd],)

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.
Load a ply point cloud, print it, and render it
PointCloud with 16384 points.
[[ 0.18328556 -0.06157751 -0.01346486]
 [ 0.15536955 -0.06336349  0.00729025]
 [ 0.01148337 -0.04533284 -0.11889685]
 ...
 [ 0.01437055 -0.04840903 -0.0394343 ]
 [-0.00084409 -0.04839408 -0.22318292]
 [-0.00786669 -0.03631293 -0.18900138]]


In [ ]:
# Part point cloud
# test set
# pcd = o3d.io.read_point_cloud("/home/zichen/Downloads/Datasets_Unpack/ShapeNetCompletion/test/partial/02691156/1169d987dbbce76775f4ea0b85a53249/00.pcd")
# train
pcd = o3d.io.read_point_cloud("/home/zichen/Downloads/Datasets_Unpack/ShapeNetCompletion/train/partial/02691156/10155655850468db78d106ce0a280f87/00.pcd")
print(pcd)
print(np.asarray(pcd.points))
o3d.visualization.draw_geometries([pcd],)

PointCloud with 1599 points.
[[-0.44124639  0.1540831   0.00212902]
 [-0.45374131  0.15436649  0.00111282]
 [-0.46792698  0.15475018  0.00071615]
 ...
 [ 0.29995024 -0.15538439  0.00423527]
 [ 0.30478823 -0.15354842 -0.00876421]
 [ 0.29378974 -0.15955749 -0.00877613]]


In [15]:
# Save camera parameters

import open3d as o3d
pcd = o3d.io.read_point_cloud("/home/zichen/Downloads/Datasets_Unpack/ShapeNetCompletion/train/partial/02691156/10155655850468db78d106ce0a280f87/00.pcd")

vis = o3d.visualization.Visualizer()
vis.create_window(width=400, height=400)
vis.add_geometry(pcd)
vis.run()  # user changes the view and press "q" to terminate
vis.get_view_control().set_zoom(0.5)   # zoom in
param = vis.get_view_control().convert_to_pinhole_camera_parameters()   # get camera parameters
o3d.io.write_pinhole_camera_parameters("PCN_Cam_Parm_save.json", param)
vis.destroy_window()

In [16]:
# Load the camera parameters and render the point cloud
import open3d as o3d
pcd = o3d.io.read_point_cloud("/home/zichen/Downloads/Datasets_Unpack/ShapeNetCompletion/train/complete/02691156/10155655850468db78d106ce0a280f87.pcd")

vis = o3d.visualization.Visualizer()
vis.create_window(width=400, height=400)
ctr = vis.get_view_control()
param = o3d.io.read_pinhole_camera_parameters("PCN_Cam_Parm_save.json")
vis.add_geometry(pcd)
ctr.convert_from_pinhole_camera_parameters(param)
vis.run()
vis.capture_screen_image("PCN_Train_Comp_0269_10155_Comp.png", do_render=True)
vis.destroy_window()


In [17]:
import open3d as o3d

pcd_8_parts = [
    "/home/zichen/Downloads/Datasets_Unpack/ShapeNetCompletion/train/partial/02691156/10155655850468db78d106ce0a280f87/00.pcd",
    "/home/zichen/Downloads/Datasets_Unpack/ShapeNetCompletion/train/partial/02691156/10155655850468db78d106ce0a280f87/01.pcd",
    "/home/zichen/Downloads/Datasets_Unpack/ShapeNetCompletion/train/partial/02691156/10155655850468db78d106ce0a280f87/02.pcd",
    "/home/zichen/Downloads/Datasets_Unpack/ShapeNetCompletion/train/partial/02691156/10155655850468db78d106ce0a280f87/03.pcd",
    "/home/zichen/Downloads/Datasets_Unpack/ShapeNetCompletion/train/partial/02691156/10155655850468db78d106ce0a280f87/04.pcd",
    "/home/zichen/Downloads/Datasets_Unpack/ShapeNetCompletion/train/partial/02691156/10155655850468db78d106ce0a280f87/05.pcd",
    "/home/zichen/Downloads/Datasets_Unpack/ShapeNetCompletion/train/partial/02691156/10155655850468db78d106ce0a280f87/06.pcd",
    "/home/zichen/Downloads/Datasets_Unpack/ShapeNetCompletion/train/partial/02691156/10155655850468db78d106ce0a280f87/07.pcd",
]

for i in range(len(pcd_8_parts)):
    pcd = o3d.io.read_point_cloud(pcd_8_parts[i])

    vis = o3d.visualization.Visualizer()
    vis.create_window(width=400, height=400)
    ctr = vis.get_view_control()
    param = o3d.io.read_pinhole_camera_parameters("PCN_Cam_Parm_save.json")
    vis.add_geometry(pcd)
    ctr.convert_from_pinhole_camera_parameters(param)
    vis.run()
    vis.capture_screen_image(f"PCN_Train_Comp_0269_10155_p{i}.png", do_render=True)
    vis.destroy_window()